# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod ‘Firebase/Core’



end
